### ISSUE TITLE
Plugin is not working for me

### ISSUE THREAD

**Issue by Elvys8** [japaniot/homebridge-dyson-robot#2]
Not sure if the problem could be the country conde.
Tried ES and SP for Spain with no luck.
![Captura de pantalla 2020-08-05 a las 1 16 22](https://user-images.githubusercontent.com/6222460/89354489-47cafa80-d6b9-11ea-85a1-f1f05aba0803.png)

`[8/5/2020, 1:10:18 AM] [Dyson 360 Heurist] FetchError: invalid json response body at https://appapi.cp.dyson.com/v2/provisioningservice/manifest reason: Unexpected end of JSON input
    at /homebridge/node_modules/homebridge-dyson-robot/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at getDevices (/homebridge/node_modules/homebridge-dyson-robot/lib/dyson-link.js:26:19)
    at DysonRobot._init (/homebridge/node_modules/homebridge-dyson-robot/lib/index.js:45:22)
 {
  type: 'invalid-json'
}
`

**Comment by benjamin-drake** [comment]
Same with me. I'm not certain it is a country code issue though. I'm fairly sure that I've got my county code right but still it does not seem to want to work. Like you the device shows up in HomeKit and like you it has the exclamation mark in the top right corner.
