### ISSUE TITLE
Plugin reporting multiple Dyson Robots in Link when only one present. 

### ISSUE THREAD

**Issue by Zydlar-Mods** [japaniot/homebridge-dyson-robot#3]
9/2/2020, 12:33:47 PM] [Dyson 360 Heurist] Error: Found more than one robot, which is currently not supported
    at DysonRobot._init (/usr/local/lib/node_modules/homebridge-dyson-robot/lib/index.js:49:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Only a single Dyson Robot (and Fan) present in Link.

**Comment by marhindev** [comment]
I had a conversation with the German Dyson support, because my Dyson had been exchanged for a new one, and now I have both in the “my Dyson “ section on their website.

they told me that they can deactivate it in their database, but it will remain (!) in the list. So it does not show up in Link, but still is preventing me from using this plugin. Too bad :-(

Any chance that more than one robot in the list will be supported? Maybe we can help with the implementation somehow?
