### ISSUE TITLE
Dyson 360 Heurist 

### ISSUE THREAD

**Issue by MichaelPils** [japaniot/homebridge-dyson-robot#8]
hello I read your entry with interest. I also own a Dyson 360 Heurist and have the plugin installed. But now I keep getting the following error message:

[DysonRobot] FetchError: invalid json response body at https://appapi.cp.dyson.com/v1/userregistration/authenticate?country=CH reason: Unexpected token < in JSON at position 0
at /usr/local/lib/node_modules/homebridge-dyson-robot/node_modules/node-fetch/lib/index.js:272:32
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at getDevices (/usr/local/lib/node_modules/homebridge-dyson-robot/lib/dyson-link.js:17:23)
at DysonRobot._init (/usr/local/lib/node_modules/homebridge-dyson-robot/lib/index.js:45:22) {
type: 'invalid-json'
}

Do you have any idea what the problem could be?
Thanks for your help

**Comment by platini76** [comment]
[10/26/2023, 5:02:43 AM] [Dyson 360] Loaded homebridge-dyson-robot v0.0.4 child bridge successfully
[10/26/2023, 5:02:43 AM] Loaded 0 cached accessories from cachedAccessories.0E51A57603C6.
[10/26/2023, 5:02:43 AM] Homebridge v1.6.1 (HAP v0.11.1) (Dyson 360) is running on port 32754.
[10/26/2023, 5:02:43 AM] [Dyson 360] FetchError: invalid json response body at https://appapi.cp.dyson.com/v1/userregistration/authenticate?country=IT reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at /var/lib/homebridge/node_modules/homebridge-dyson-robot/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getDevices (/var/lib/homebridge/node_modules/homebridge-dyson-robot/lib/dyson-link.js:17:23)
    at DysonRobot._init (/var/lib/homebridge/node_modules/homebridge-dyson-robot/lib/index.js:45:22) {
  type: 'invalid-json'
}

same here.
